language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
# command to install dependencies
install:
  - pip install --user pytest
  - pip install --user .
# command to run tests
script:
  - cd tests && pytest
