language: python
python:
  - "3.6"
  - "nightly"
#  - "3.7-dev" # For now 3.7 have problems with travis
# command to install dependencies
install:
  - pip install --upgrade pip
  - pip install --upgrade setuptools
  - pip install pytest
  - pip install pytest-mypy
  - python setup.py install
# command to run tests
script:
  - cd tests
  - MYPYPATH=$PWD/..:$MYPYPATH pytest --mypy
